name: dart_pad
author: Dart Team <misc@dartlang.org>
description: The UI client for a web based interactive Dart service.
homepage: https://github.com/dart-lang/dart-pad
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  _discoveryapis_commons: '>=0.1.0 <0.2.0'
  browser: ^0.10.0+2
  codemirror: ^0.4.1
  haikunator: ^0.1.0
  frappe: ^0.4.0
  http: '>=0.11.1 <0.12.0'
  logging: '>=0.9.0 <0.12.0'
  markdown: ^1.0.0
  route_hierarchical: ^0.7.0
dev_dependencies:
  dart_to_js_script_rewriter: any
  git: any
  grinder: ^0.8.0
  librato: ^0.1.0
  test: ^0.12.0
  which: ^0.1.0
  yaml: any
transformers:
- dart_to_js_script_rewriter
- $dart2js:
    commandLineOptions: [--enable-experimental-mirrors]
    $exclude:
    - test/all.dart
    - test/sauce.dart
    - test/web_integration.dart
    - web/packages/csslib/css.dart
